name: GitHub Actions

on: [push]

jobs:
  Build-Project-Linux:
    name: Build Project on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install CMake
        run: sudo apt-get install -y cmake

      - name: Configure and Build
        run: |
          cmake -H. -B_build
          cmake --build _build

      - name: Run tests
        run: ./_build/tests

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: built-files
          path: _build/example

  Build-Project-Windows:
    name: Build Project on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; `
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; `
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Install CMake
        run: choco install cmake -y

      - name: Configure and Build
        run: |
          mkdir _build
          cd _build
          cmake ..
          cmake --build .

      - name: Run tests
        run: .\_build\tests.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: built-files
          path: _build\example
